/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import entities.DetailLembur;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Toolkit;
import java.io.File;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author hp
 */
public class OverTimeView extends javax.swing.JFrame {

    PegawaiView pegawaiView;
    JabatanView jabatanView;
    DetailView detailView;
    JenisLemburView jenisLemburView;
    DetailLemburView detailLemburView; 
    DetailLemburViaAdminView detailLemburViaAdminView;
    LaporanLembur laporanLembur;

    /**
     * Creates new form OverTimeView
     */
    public OverTimeView() {
        initComponents();
        pegawaiView = new PegawaiView();
        jabatanView = new JabatanView();
        detailView = new DetailView();
        jenisLemburView = new JenisLemburView();
        detailLemburView = new DetailLemburView();
        laporanLembur = new LaporanLembur();
        detailLemburViaAdminView = new DetailLemburViaAdminView();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(dim.width, dim.height);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuPegawai = new javax.swing.JMenuItem();
        menujabatan = new javax.swing.JMenuItem();
        menuLembur = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuLemburKaryawan = new javax.swing.JMenuItem();
        menuDetailLembur = new javax.swing.JMenuItem();
        menuDetailLemburJabatan = new javax.swing.JMenuItem();
        menuReport = new javax.swing.JMenu();
        laporanLemburPegawai = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("jMenu6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(697, 634));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 952, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 634, Short.MAX_VALUE)
        );

        jMenu1.setText("Master");

        menuPegawai.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        menuPegawai.setText("Pegawai");
        menuPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPegawaiActionPerformed(evt);
            }
        });
        jMenu1.add(menuPegawai);

        menujabatan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
        menujabatan.setText("Jabatan");
        menujabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menujabatanActionPerformed(evt);
            }
        });
        jMenu1.add(menujabatan);

        menuLembur.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, 0));
        menuLembur.setText("Jenis Lembur");
        menuLembur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLemburActionPerformed(evt);
            }
        });
        jMenu1.add(menuLembur);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Transaksi");

        menuLemburKaryawan.setText("Detail Lembur (Karyawan)");
        menuLemburKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLemburKaryawanActionPerformed(evt);
            }
        });
        jMenu2.add(menuLemburKaryawan);

        menuDetailLembur.setText("Detail Lembur");
        menuDetailLembur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDetailLemburActionPerformed(evt);
            }
        });
        jMenu2.add(menuDetailLembur);

        menuDetailLemburJabatan.setText("Detail Lembur Jabatan");
        menuDetailLemburJabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDetailLemburJabatanActionPerformed(evt);
            }
        });
        jMenu2.add(menuDetailLemburJabatan);

        jMenuBar1.add(jMenu2);

        menuReport.setText("Laporan");
        menuReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportActionPerformed(evt);
            }
        });

        laporanLemburPegawai.setText("Laporan Lembur Pegawai");
        laporanLemburPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanLemburPegawaiActionPerformed(evt);
            }
        });
        menuReport.add(laporanLemburPegawai);

        jMenuBar1.add(menuReport);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 952, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPegawaiActionPerformed
        if (!pegawaiView.getVisible() && !pegawaiView.isShowing()) {
            pegawaiView = new PegawaiView();
            jDesktopPane1.add(pegawaiView);
            pegawaiView.setVisible(true);
        }
    }//GEN-LAST:event_menuPegawaiActionPerformed

    private void menuLemburActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLemburActionPerformed
        if (!jenisLemburView.getVisible() && !jenisLemburView.isShowing()) {
            jenisLemburView = new JenisLemburView();
            jDesktopPane1.add(jenisLemburView);
            jenisLemburView.setVisible(true);
        }
    }//GEN-LAST:event_menuLemburActionPerformed

    private void menujabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menujabatanActionPerformed
        if (!jabatanView.getVisible() && !jabatanView.isShowing()) {
            jabatanView = new JabatanView();
            jDesktopPane1.add(jabatanView);
            jabatanView.setVisible(true);
        }
    }//GEN-LAST:event_menujabatanActionPerformed

    private void menuDetailLemburJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDetailLemburJabatanActionPerformed
        if (!detailView.getVisible() && !detailView.isShowing()) {
            detailView = new DetailView();
            jDesktopPane1.add(detailView);
            detailView.setVisible(true);
        }
    }//GEN-LAST:event_menuDetailLemburJabatanActionPerformed

    private void menuDetailLemburActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDetailLemburActionPerformed
        if (!detailLemburViaAdminView.getVisible() && !detailLemburViaAdminView.isShowing()) {
            detailLemburViaAdminView = new DetailLemburViaAdminView();
            jDesktopPane1.add(detailLemburViaAdminView);
            detailLemburViaAdminView.setVisible(true);
        }
    }//GEN-LAST:event_menuDetailLemburActionPerformed

    private void menuReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportActionPerformed

    }//GEN-LAST:event_menuReportActionPerformed

    private void laporanLemburPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanLemburPegawaiActionPerformed
        if (!laporanLembur.getVisible() && !laporanLembur.isShowing()) {
            laporanLembur = new LaporanLembur();
            jDesktopPane1.add(laporanLembur);
            laporanLembur.setVisible(true);
        }
    }//GEN-LAST:event_laporanLemburPegawaiActionPerformed

    private void menuLemburKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLemburKaryawanActionPerformed
        if (!detailLemburView.getVisible() && !detailLemburView.isShowing()) {
            detailLemburView = new DetailLemburView();
            jDesktopPane1.add(detailLemburView);
            detailLemburView.setVisible(true);
        }
    }//GEN-LAST:event_menuLemburKaryawanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OverTimeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OverTimeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OverTimeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OverTimeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        LaunchProgressBar pb = new LaunchProgressBar();
        pb.setVisible(true);
        for (int i = 0; i <= 100; i++) {
            try {
                pb.getProgressBar().setValue(i);
                Thread.sleep(25);
            } catch (InterruptedException ex) {
                Logger.getLogger(LaunchProgressBar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        pb.dispose();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OverTimeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem laporanLemburPegawai;
    private javax.swing.JMenuItem menuDetailLembur;
    private javax.swing.JMenuItem menuDetailLemburJabatan;
    private javax.swing.JMenuItem menuLembur;
    private javax.swing.JMenuItem menuLemburKaryawan;
    private javax.swing.JMenuItem menuPegawai;
    private javax.swing.JMenu menuReport;
    private javax.swing.JMenuItem menujabatan;
    // End of variables declaration//GEN-END:variables
}
